import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 
    <html lang="en">
      <body className={inter.className}
       data-new-gr-c-s-check-loaded="14.1092.0"
         data-gr-ext-installed=""
         cz-shortcut-listen="true"
      >
        <Navbar/>
<main>
{children}
</main>   
        
        <Footer/>
    
        </body>

    </html>

  );
}

